import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { ethers } from "ethers";

export default function Home() {
  const [walletAddress, setWalletAddress] = useState();
  const [balance, setBalance] = useState();

  const requestAccounts = async () => {
    if (window.ethereum) {
      try {
        const accounts = await window.ethereum.request({
          method: "eth_requestAccounts",
        });

        setWalletAddress(accounts[0]);
      } catch (err) {
        console.error(err);
      }
    }
  };

  const connectWallet = async () => {
    if (typeof window.ethereum !== "undefined") {
      await requestAccounts();
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const ethBalance = await provider.getBalance("ethers.eth");
      setBalance(ethers.utils.formatEther(ethBalance));
    }
  };

  const disconectWallet = async () => {
    setWalletAddress(null);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Web #</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Web3!</h1>

        {walletAddress && (
          <p className={styles.description}>
            <div>
              {" "}
              Address: <code className={styles.code}>{walletAddress}</code>
            </div>
          </p>
        )}

        {walletAddress && balance && (
          <p className={styles.description}>
            {balance ? (
              <div>
                {" "}
                Balance: <code className={styles.code}>{balance}</code>
              </div>
            ) : (
              <div>Loading balance...</div>
            )}
          </p>
        )}

        <div className={styles.buttonWrapper}>
          {!walletAddress ? (
            <button onClick={connectWallet} className={styles.button}>
              Connect Wallet
            </button>
          ) : (
            <button onClick={disconectWallet} className={styles.button}>
              Disconnect Wallet
            </button>
          )}
        </div>
      </main>
    </div>
  );
}
